pyodide:
	@echo "Building Pyodide..."
	wget https://github.com/pyodide/pyodide/releases/download/0.26.4/pyodide-0.26.4.tar.bz2
	tar -xf pyodide-0.26.4.tar.bz2
	mkdir -p public && mv pyodide public/pyodide
